// Copyright 2026 spark_isaac_mycobot_demo contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ---------------------------------------------------------------------------
// PROJECT CONTEXT — PHASE 3 DRIVER: This node is the safety-gated funnel
// between the learned policy and the robot's serial port:
//
//   /mycobot/policy/inference (PolicyInference, from the ONNX node)
//        |  1. drop messages the inference stage already rejected
//        |  2. hard-gate through evaluate_safety_boundaries()
//        |  3. encode surviving targets into pymycobot serial bytes
//        v
//   /mycobot/hardware/serial_command (SerialCommand)
//
// In the mock ecosystem the SerialCommand messages are consumed by tests;
// on real hardware this same node would write packet bytes to /dev/ttyUSB0
// (or hand them to pymycobot). Keeping the gate in a compiled C++ node
// gives deterministic, low-latency rejection independent of the Python
// policy stack — a defense-in-depth layer below the neural network.
// ---------------------------------------------------------------------------

#include <array>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
// Custom message headers are GENERATED by rosidl from the .msg files in
// msg/ at build time. Naming convention: PolicyInference.msg becomes
// spark_verify_pkg/msg/policy_inference.hpp with type
// spark_verify_pkg::msg::PolicyInference.
#include "spark_verify_pkg/msg/policy_inference.hpp"
#include "spark_verify_pkg/msg/serial_command.hpp"
#include "spark_verify_pkg/pymycobot_serial_encoder.hpp"
#include "spark_verify_pkg/safety_boundary_evaluator.hpp"

namespace spark_verify_pkg
{

class PymycobotDriver : public rclcpp::Node
{
public:
  PymycobotDriver()
  : Node("pymycobot_driver")
  {
    // Topic names are parameters so the launch file can rewire the node
    // (e.g. point it at a bag replay) without code changes.
    declare_parameter<std::string>("inference_topic", "/mycobot/policy/inference");
    declare_parameter<std::string>("serial_topic", "/mycobot/hardware/serial_command");

    const auto inference_topic = get_parameter("inference_topic").as_string();
    const auto serial_topic = get_parameter("serial_topic").as_string();

    serial_pub_ = create_publisher<spark_verify_pkg::msg::SerialCommand>(serial_topic, 10);
    inference_sub_ = create_subscription<spark_verify_pkg::msg::PolicyInference>(
      inference_topic, 10,
      std::bind(&PymycobotDriver::on_inference, this, std::placeholders::_1));
  }

private:
  void on_inference(const spark_verify_pkg::msg::PolicyInference::SharedPtr msg)
  {
    // Gate 1: upstream stages set accepted=false for inferences they have
    // already invalidated (e.g. latency overruns); honor that verdict.
    if (!msg->accepted) {
      RCLCPP_WARN(get_logger(), "Skipping rejected policy inference message");
      return;
    }

    // PolicyInference.joint_targets_rad is declared float32[6] in the .msg
    // file — a FIXED-size array, so indexing 0..5 is always in bounds.
    std::array<double, kMyCobotDof> joint_positions{};
    std::array<double, kMyCobotDof> joint_velocities{};  // zeros: mock has no velocity estimate
    for (std::size_t idx = 0; idx < kMyCobotDof; ++idx) {
      joint_positions[idx] = msg->joint_targets_rad[idx];
    }

    // Gate 2: the deterministic safety evaluator. The end-effector sample
    // point (0.1, 0.0, 0.2) is a fixed in-workspace stand-in because the
    // mock does not compute forward kinematics here; a live driver would
    // feed the FK solution of the commanded pose.
    SafetyBoundaryConfig config;
    const auto safety = evaluate_safety_boundaries(
      config, joint_positions, joint_velocities, 0.1, 0.0, 0.2);
    if (safety.boundary_violated) {
      // This is the assertion target of the Phase 3 integration test:
      // out-of-bound targets must die HERE, before any bytes are formed.
      RCLCPP_WARN(get_logger(), "Rejected out-of-bound joint inference before serial transmit");
      return;
    }

    // Gate passed: encode to pymycobot wire format and publish. Copying
    // msg->header preserves the original camera-frame timestamp, so the
    // full perception -> inference -> serial latency chain can be measured
    // by comparing header.stamp to receive time.
    const auto packet = encode_send_angles_packet(joint_positions);
    spark_verify_pkg::msg::SerialCommand serial;
    serial.header = msg->header;
    serial.command_id = kPymycobotSendAnglesCommand;
    serial.payload.assign(packet.begin(), packet.end());
    serial_pub_->publish(serial);
  }

  rclcpp::Publisher<spark_verify_pkg::msg::SerialCommand>::SharedPtr serial_pub_;
  rclcpp::Subscription<spark_verify_pkg::msg::PolicyInference>::SharedPtr inference_sub_;
};

}  // namespace spark_verify_pkg

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<spark_verify_pkg::PymycobotDriver>());
  rclcpp::shutdown();
  return 0;
}
